on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21  # Use Java SDK 21
          distribution: 'temurin'

      # Step 3: Cache dependencies
      - name: Set up cache for Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build and test
      - name: Build with Maven
        run: mvn clean install
      # Step 5 : Run unit tests
      - name: Run tests with Maven
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Deploy to production
        run: echo "Deploy your application here"

